version: '3.8'

services:
  serumpun-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: serumpun-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - APP_PORT=8080
    networks:
      - serumpun-network

networks:
  serumpun-network:
    driver: bridge
